(load "2.23.scm")			;for-each
(load "2.46.scm")			;vector
(load "2.47.scm")			;frame
(load "2.48.scm")			;segment

(define (frame-coord-map frame)
  (lambda (v)
    (add-vect
     (origin-frame frame)
     (add-vect (scale-vect (xcor-vect v) (edge1-frame frame))
	       (scale-vect (ycor-vect v) (edge2-frame frame))))))
(define (segments->painter segment-list)
  (lambda (frame)
    (for-each
     (lambda (segment)
       (draw-line
	((frame-coord-map frame)
	 (start-segment segment))
	((frame-coord-map frame)
	 (end-segment segment))))
     segment-list)))
;; a)
(define outline
  (let ((v1 (make-vect 0 0))
	(v2 (make-vect 1 0))
	(v3 (make-vect 1 1))
	(v4 (make-vect 0 1)))
    (segments->painter
     (list (make-segment v1 v2)
	   (make-segment v2 v3)
	   (make-segment v3 v4)
	   (make-segment v4 v1)))))
;; b)
(define cross
  (let ((v1 (make-vect 0 0))
	(v2 (make-vect 1 0))
	(v3 (make-vect 1 1))
	(v4 (make-vect 0 1)))
    (segments->painter
     (list (make-segment v1 v3)
	   (make-segment v2 v4)))))
;; c)
(define diamond
  (let ((v1 (make-vect 0.5 0.0))
	(v2 (make-vect 1.0 0.5))
	(v3 (make-vect 0.5 1.0))
	(v4 (make-vect 0.0 0.5)))
    (segments->painter
     (list (make-segment v1 v2)
	   (make-segment v2 v3)
	   (make-segment v3 v4)
	   (make-segment v4 v1)))))
;; d)
(define wave
  (let ((left-innerleg    (make-vect 0.40 0.00))
	(left-crotch      (make-vect 0.45 0.40))
	(left-outerleg    (make-vect 0.30 0.00))
	(left-armpit      (make-vect 0.38 0.60))
	(left-armpit-ext  (make-vect 0.30 0.60))
	(left-elbow       (make-vect 0.20 0.50))
	(left-underhand   (make-vect 0.00 0.60))
	(left-overhand    (make-vect 0.00 0.70))
	(left-overelbow   (make-vect 0.20 0.60))
	(left-overarmpit  (make-vect 0.30 0.70))
	(left-shoulder    (make-vect 0.40 0.70))
	(left-middlehead  (make-vect 0.35 0.85))
	(left-mouth       (make-vect 0.40 0.80))
	(left-tophead     (make-vect 0.40 1.00))
	(middle-mouth     (make-vect 0.50 0.78))
	(right-crotch     (make-vect 0.55 0.40))
	(right-innerleg   (make-vect 0.60 0.00))
	(right-outerleg   (make-vect 0.70 0.00))
	(right-armpit     (make-vect 0.62 0.60))
	(right-armpit-ext (make-vect 0.70 0.60))
	(right-underhand  (make-vect 1.00 0.30))
	(right-overhand   (make-vect 1.00 0.35))
	(right-overarmpit (make-vect 0.70 0.70))
	(right-shoulder   (make-vect 0.60 0.70))
	(right-middlehead (make-vect 0.65 0.85))
	(right-mouth      (make-vect 0.60 0.80))
	(right-tophead    (make-vect 0.60 1.00)))
    (segments->painter
     (list (make-segment left-innerleg    left-crotch)
	   (make-segment left-crotch      right-crotch)
	   (make-segment right-crotch   right-innerleg)
	   ;; left side
	   (make-segment left-outerleg    left-armpit)
	   (make-segment left-armpit      left-armpit-ext)
	   (make-segment left-armpit-ext  left-elbow)
	   (make-segment left-elbow       left-underhand)
	   (make-segment left-overhand    left-overelbow)
	   (make-segment left-overelbow   left-overarmpit)
	   (make-segment left-overarmpit  left-shoulder)
	   (make-segment left-shoulder    left-middlehead)
	   (make-segment left-middlehead  left-tophead)
	   ;; right side
	   (make-segment right-outerleg   right-armpit)
	   (make-segment right-armpit     right-armpit-ext)
	   (make-segment right-armpit-ext right-underhand)
	   (make-segment right-overhand   right-overarmpit)
	   (make-segment right-overarmpit right-shoulder)
	   (make-segment right-shoulder   right-middlehead)
	   (make-segment right-middlehead right-tophead)))))
